### ISSUE TITLE
Allow custom awc Client for fetching OIDC configuration

### ISSUE THREAD

**Issue by thomasdarimont** [spectare/actix-4-jwt-auth#21]
Currently  the OIDC configuration is fetched with a default awc Client. Although this is convenient, it does not support fetching OpenID configuration from providers that use self-signed certificates, e.g. in local test environments. 

```
[2023-04-06T09:26:21Z WARN  rustls::conn] Sending fatal alert BadCertificate
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ConnectivityError(Connect(Io(Custom { kind: InvalidData, error: InvalidCertificateData("invalid peer certificate: UnknownIssuer") })))', apps/api-actix/src/main.rs:21:87
stack backtrace:
````

See: `let client = awc::Client::default();`.  in https://github.com/spectare/actix-4-jwt-auth/blob/main/src/oidc.rs#L106

It would be great if actix-4-jwt-auth would allow users to provide their own awc Client that they could configure appropriately. This would also also to use a client with openssl instead of rusttls

**Comment by thomasdarimont** [comment]
Perhaps we could also use a "default" client provided to Actix itself, such that all requests use the same http client.

**Comment by thomasdarimont** [comment]
My current workaround is fetching the JWKSKeySet with a custom awc client with openssl and than create the OidcConfig from the JWKS:

```
...
    // workaround for fix default awc client used by OidcConfig::Issuer
    let oidc = fetch_oidc_config(&config).await;
    //let oidc = Oidc::new(OidcConfig::Issuer(config.oidc_issuer.clone().into())).await.unwrap();
...

async fn fetch_oidc_config(config: &Config) -> Oidc {

    // fetch jwks, and construct OidcConfig from JWKS set

    let client_tls_config = SslConnector::builder(SslMethod::tls()).unwrap() //
        .build();

    let client = awc::Client::builder() //
        .add_default_header((header::USER_AGENT, "api-actix/0.1.0")) //
        .connector(Connector::new().openssl(client_tls_config)) //
        .finish();

    let jwks_key_set = client.get(config.oidc_issuer.as_str().to_string() + "/protocol/openid-connect/certs").send().await //
        .unwrap().json::<JWKSet<Empty>>().await.unwrap();

    Oidc::new(OidcConfig::Jwks(jwks_key_set)).await.unwrap()
}
```

**Comment by olger** [comment]
Hi @thomasdarimont, 

Do you have a sample oidc config that's using self signed certificates ?

Using ```Oidc::new(OidcConfig::Jwks(your_jwks_key_set)``` is indeed the way to setup when you like to use your own keys.
