### ISSUE TITLE
Configure token lookup location

### ISSUE THREAD

**Issue by bangbaew** [spectare/actix-4-jwt-auth#31]
The Gofiber JWT middleware provides flexibility in configuring the token lookup location, allowing adherence to OpenAPI specifications. The `TokenLookup` key supports options such as Cookie, Header, Path, and Query. The default setting is `"header:Authorization"`, mirroring the behavior of this crate. However, in my frontend website, where I store the access token in cookies, ensuring compliance with OpenAPI specs, to transmit the access token to the Authorization header, the cookie cannot be set as `HttpOnly`, compromising security. Therefore, I aim to maintain `HttpOnly` while employing this crate to extract the token by reading cookies with a custom key.

![image](https://github.com/spectare/actix-4-jwt-auth/assets/29559559/9aca1ac1-5acc-46d7-a445-89ceeeaa224c)

**Comment by bangbaew** [comment]
I opened a PR #32
currently support custom header and cookie.

**Comment by olger** [comment]
Thanks, I'll have a look.

**Comment by olger** [comment]
Thanks for your addition, merged it and will release a 1.2.0 for it.
