### ISSUE TITLE
Add support for passing custom ValidationOptions via OIDCValidatorConfig

### ISSUE THREAD

**Issue by thomasdarimont** [spectare/actix-4-jwt-auth#6]
Currently the Validation options seems to be hardcoded in https://github.com/spectare/actix-4-jwt-auth/blob/main/src/lib.rs#L160.

It would be useful if those options could be passed via the `OIDCValidatorConfig`.

**Comment by olger** [comment]
Hi Thomas,

Anything specific you like to achieve ? 
At this moment  the use of Biscuit is hidden 'inside'. wrapping something around it is a possibility, preferably to match your use case. 

Cheers, 

Olger

**Comment by olger** [comment]
Supported in 0.6.0
